# Generated by Django 4.2.3 on 2023-12-29 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('expedition_id', models.AutoField(primary_key=True, serialize=False)),
                ('expedition', models.CharField(blank=True, max_length=100)),
                ('continent', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('taxonomy_id', models.AutoField(primary_key=True, serialize=False)),
                ('kingdom', models.CharField(blank=True, max_length=50)),
                ('phylum', models.CharField(blank=True, max_length=50)),
                ('highest_biostratigraphic_zone', models.CharField(blank=True, max_length=50)),
                ('class_name', models.CharField(blank=True, max_length=50)),
                ('identification_description', models.CharField(blank=True, max_length=50)),
                ('family', models.CharField(blank=True, max_length=50)),
                ('genus', models.CharField(blank=True, max_length=50)),
                ('species', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('specimen_id', models.AutoField(primary_key=True, serialize=False)),
                ('catalog_number', models.CharField(blank=True, max_length=50)),
                ('created', models.IntegerField()),
                ('expedition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='specimen_catalog.expedition')),
                ('taxonomy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='specimen_catalog.taxonomy')),
            ],
            options={
                'ordering': ['-specimen_id'],
            },
        ),
    ]
