# Generated by Django 4.2.3 on 2023-12-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimen_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specimen',
            options={'ordering': ['-specimen_id']},
        ),
        migrations.AlterField(
            model_name='expedition',
            name='continent',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='expedition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='state_province',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='term',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='catalog_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='class_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='family',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='genus',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='highest_biostratigraphic_zone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='identification_description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='kingdom',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='phylum',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='species',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
