# Generated by Django 4.2.3 on 2023-12-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimen_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='created',
            field=models.IntegerField(default=0),
        ),
    ]
