# Generated by Django 4.2.3 on 2023-12-31 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specimen_catalog', '0002_alter_specimen_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specimen',
            name='created',
        ),
    ]
