# Generated by Django 4.2.3 on 2023-12-31 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specimen_catalog', '0004_specimen_continent_specimen_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specimen',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='specimen',
            name='country',
        ),
    ]
